import styles from './styles.module.css'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Next 13 | About',
  description: 'Generated by create next app',
}
export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <h1>About Nav Bar</h1>
      <main className={styles.main}>
        {children}
      </main>
    </>
  )
}